build-windows:
  tags:
    - windows
  only:
    - main
  script:
    - dotnet publish src/BinaryLane.Cli -r win-x64 -c Release
  artifacts:
    paths:
      - src/BinaryLane.Cli/bin/Release/net10.0/win-x64/publish/bl.exe
