using System.Text;

namespace BinaryLane.Cli.Generator;

/// <summary>
/// Generates C# command classes using System.CommandLine 2.0 stable API.
/// API: Options.Add(), Arguments.Add(), Subcommands.Add(), SetAction(), parseResult.GetValue().
/// </summary>
public static class CommandEmitter
{
    private static readonly HashSet<string> CSharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while", "async", "await", "type",
    ];

    private static string SafeId(string name) =>
        CSharpKeywords.Contains(name) ? "@" + name : name;

    public static string Emit(OperationInfo op)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.CommandLine;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using BinaryLane.Cli.Commands;");
        sb.AppendLine("using BinaryLane.Cli.Infrastructure.Json;");
        sb.AppendLine("using BinaryLane.Cli.Infrastructure.Output;");
        sb.AppendLine();
        sb.AppendLine("namespace BinaryLane.Cli.Generated.Commands;");
        sb.AppendLine();
        sb.AppendLine($"public static class {op.ClassName}");
        sb.AppendLine("{");

        var parts = op.CliCommand.Split(' ');
        var commandName = parts[^1];
        var description = OperationInfo.NormalizeDescription(op.Summary).Replace("\"", "\\\"");

        sb.AppendLine("    public static Command Create()");
        sb.AppendLine("    {");
        sb.AppendLine($"        var command = new Command(\"{commandName}\", \"{description}\");");

        // Path parameter arguments (positional)
        foreach (var param in op.PathParameters)
        {
            var argName = SafeId(OperationInfo.ToCamelCase(param.Name));
            var optionDesc = Esc(param.Description);
            sb.AppendLine();
            sb.AppendLine($"        var {argName}Arg = new Argument<string>(\"{param.Name}\") {{ Description = \"{optionDesc}\" }};");
            sb.AppendLine($"        command.Arguments.Add({argName}Arg);");
        }

        // Query parameter options
        foreach (var param in op.QueryParameters)
        {
            var optName = param.Name.Replace('_', '-');
            var varName = SafeId(OperationInfo.ToCamelCase(param.Name)) + "Opt";
            var optionDesc = Esc(param.Description);
            var csharpType = MapType(param.Type, param.Required);

            sb.AppendLine();
            if (param.IsEnum && param.EnumValues != null)
            {
                sb.AppendLine($"        var {varName} = new Option<string?>(\"{Prefix(optName)}{optName}\") {{ Description = \"{optionDesc}\" }};");
                sb.AppendLine($"        {varName}.AcceptOnlyFromAmong({string.Join(", ", param.EnumValues.Select(v => $"\"{v}\""))});");
            }
            else
            {
                sb.AppendLine($"        var {varName} = new Option<{csharpType}>(\"{Prefix(optName)}{optName}\") {{ Description = \"{optionDesc}\" }};");
            }
            sb.AppendLine($"        command.Options.Add({varName});");
        }

        // Body property options
        foreach (var prop in op.BodyProperties)
        {
            var optName = prop.Name.Replace('_', '-');
            var varName = SafeId(OperationInfo.ToCamelCase(prop.Name)) + "Opt";
            var optionDesc = Esc(prop.Description);

            sb.AppendLine();
            if (prop.IsArray)
            {
                sb.AppendLine($"        var {varName} = new Option<string[]>(\"{Prefix(optName)}{optName}\") {{ Description = \"{optionDesc}\", AllowMultipleArgumentsPerToken = true }};");
            }
            else if (prop.IsEnum && prop.EnumValues != null)
            {
                sb.AppendLine($"        var {varName} = new Option<string{(prop.Required ? "" : "?")}>(\"--{optName}\") {{ Description = \"{optionDesc}\" }};");
                sb.AppendLine($"        {varName}.AcceptOnlyFromAmong({string.Join(", ", prop.EnumValues.Select(v => $"\"{v}\""))});");
            }
            else
            {
                var csharpType = MapType(prop.Type, prop.Required);
                sb.AppendLine($"        var {varName} = new Option<{csharpType}>(\"--{optName}\") {{ Description = \"{optionDesc}\" }};");
            }

            if (prop.Required)
                sb.AppendLine($"        {varName}.Required = true;");

            sb.AppendLine($"        command.Options.Add({varName});");
        }

        // Handler
        sb.AppendLine();
        sb.AppendLine("        command.SetAction(async (parseResult, ct) =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var cmdCtx = ContextBinder.Bind(parseResult);");

        // Read path parameter values
        foreach (var param in op.PathParameters)
        {
            var argName = SafeId(OperationInfo.ToCamelCase(param.Name));
            sb.AppendLine($"            var {argName} = parseResult.GetValue({argName}Arg)!;");
        }

        // Read query parameter values
        foreach (var param in op.QueryParameters)
        {
            var varName = SafeId(OperationInfo.ToCamelCase(param.Name));
            sb.AppendLine($"            var {varName} = parseResult.GetValue({varName}Opt);");
        }

        // Read body property values
        foreach (var prop in op.BodyProperties)
        {
            var varName = SafeId(OperationInfo.ToCamelCase(prop.Name));
            sb.AppendLine($"            var {varName} = parseResult.GetValue({varName}Opt);");
        }

        // Build URL
        var urlPath = op.Path.TrimStart('/');
        foreach (var param in op.PathParameters)
        {
            var argName = SafeId(OperationInfo.ToCamelCase(param.Name));
            urlPath = urlPath.Replace($"{{{param.Name}}}", $"{{{argName}}}");
        }
        var fragmentIndex = urlPath.IndexOf('#');
        if (fragmentIndex >= 0)
            urlPath = urlPath[..fragmentIndex];

        // Query string
        bool hasQueryParams = op.QueryParameters.Count > 0;
        if (hasQueryParams)
        {
            sb.AppendLine();
            sb.AppendLine("            var queryParts = new List<string>();");
            foreach (var param in op.QueryParameters)
            {
                var varName = SafeId(OperationInfo.ToCamelCase(param.Name));
                sb.AppendLine($"            if ({varName} != null) queryParts.Add($\"{param.Name}={{Uri.EscapeDataString({varName}.ToString()!)}}\");");
            }
            sb.AppendLine("            var queryString = queryParts.Count > 0 ? \"?\" + string.Join(\"&\", queryParts) : \"\";");
        }

        // Body JSON
        bool hasBody = op.BodyProperties.Count > 0 || op.DiscriminatorValue != null;
        if (hasBody)
        {
            sb.AppendLine();
            sb.AppendLine("            var body = new Dictionary<string, object?>();");
            if (op.DiscriminatorValue != null)
            {
                sb.AppendLine($"            body[\"type\"] = \"{op.DiscriminatorValue}\";");
            }
            foreach (var prop in op.BodyProperties)
            {
                var varName = SafeId(OperationInfo.ToCamelCase(prop.Name));
                bool isValueType = prop.Type is "int" or "double" or "bool" or "DateTime";
                if (prop.Required && isValueType)
                    sb.AppendLine($"            body[\"{prop.Name}\"] = {varName};");
                else if (prop.IsArray)
                    sb.AppendLine($"            if ({varName} is {{ Length: > 0 }}) body[\"{prop.Name}\"] = {varName};");
                else if (prop.IsUnionType)
                    sb.AppendLine($"            if ({varName} != null) body[\"{prop.Name}\"] = int.TryParse({varName}, out var {varName}Num) ? (object?){varName}Num : {varName};");
                else
                    sb.AppendLine($"            if ({varName} != null) body[\"{prop.Name}\"] = {varName};");
            }
        }

        // Field selection for list commands
        bool isList = op.IsPaginated || op.DefaultFields.Count > 0;
        if (isList)
        {
            sb.AppendLine();
            sb.Append("            string[] defaultFields = [");
            sb.Append(string.Join(", ", op.DefaultFields.Select(f => $"\"{f}\"")));
            sb.AppendLine("];");
            sb.AppendLine("            var fields = cmdCtx.FormatFields?.Split(',').Select(f => f.Trim()).ToList()");
            sb.AppendLine("                ?? defaultFields.ToList();");
        }

        // Execute request
        sb.AppendLine();
        sb.AppendLine("            return await ApiCommandBase.ExecuteApiCallAsync(");
        sb.AppendLine("                cmdCtx,");

        if (op.IsPaginated)
        {
            var urlArg = hasQueryParams ? $"$\"{urlPath}{{queryString}}\"" : $"$\"{urlPath}\"";
            sb.AppendLine($"                client => ApiCommandBase.ExecutePaginatedAsync(client, {urlArg}),");
        }
        else
        {
            var urlExpr = hasQueryParams ? $"$\"{urlPath}{{queryString}}\"" : $"$\"{urlPath}\"";
            var jsonContent = $"new StringContent(JsonSerializer.Serialize(body, CliJsonContext.Default.DictionaryStringObject), Encoding.UTF8, \"application/json\")";
            var methodCall = op.HttpMethod switch
            {
                "GET" => $"client.GetAsync({urlExpr}, ct)",
                "DELETE" => $"client.DeleteAsync({urlExpr}, ct)",
                "POST" when hasBody => $"client.PostAsync({urlExpr}, {jsonContent}, ct)",
                "POST" => $"client.PostAsync({urlExpr}, null, ct)",
                "PUT" when hasBody => $"client.PutAsync({urlExpr}, {jsonContent}, ct)",
                "PUT" => $"client.PutAsync({urlExpr}, null, ct)",
                "PATCH" when hasBody => $"client.PatchAsync({urlExpr}, {jsonContent}, ct)",
                "PATCH" => $"client.PatchAsync({urlExpr}, null, ct)",
                _ => $"client.GetAsync({urlExpr}, ct)",
            };
            sb.AppendLine($"                async client => await {methodCall},");
        }

        if (isList)
        {
            sb.AppendLine("                json =>");
            sb.AppendLine("                {");
            sb.AppendLine("                    var primary = ResponseFlattener.ExtractPrimary(json);");
            sb.AppendLine("                    return ResponseFlattener.FlattenList(primary, fields);");
            sb.AppendLine("                });");
        }
        else
        {
            sb.AppendLine("                null);");
        }

        sb.AppendLine("        });");
        sb.AppendLine();
        sb.AppendLine("        return command;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Prefix(string optName) => optName.Length == 1 ? "-" : "--";

    private static string MapType(string type, bool required)
    {
        var csharp = type switch
        {
            "int" => "int",
            "double" => "double",
            "bool" => "bool",
            "DateTime" => "DateTime",
            _ => "string",
        };
        return required ? csharp : csharp + "?";
    }

    private static string Esc(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", "");
}
