using System.Text;

namespace BinaryLane.Cli.Generator;

/// <summary>
/// Generates the CommandRegistry class that builds the System.CommandLine command tree.
/// Uses 2.0 API: Subcommands.Add() instead of AddCommand().
/// </summary>
public static class RegistryEmitter
{
    public static string Emit(List<OperationInfo> operations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.CommandLine;");
        sb.AppendLine();
        sb.AppendLine("namespace BinaryLane.Cli.Generated.Commands;");
        sb.AppendLine();
        sb.AppendLine("public static class CommandRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static void Register(RootCommand root)");
        sb.AppendLine("    {");

        // Collect all unique group commands (non-leaf paths)
        var groups = new Dictionary<string, string>();
        var leafCommands = new List<(string[] parts, string className)>();

        foreach (var op in operations.OrderBy(o => o.CliCommand))
        {
            var parts = op.CliCommand.Split(' ');
            leafCommands.Add((parts, op.ClassName));

            for (int i = 1; i < parts.Length; i++)
            {
                var groupPath = string.Join(' ', parts[..i]);
                if (!groups.ContainsKey(groupPath))
                {
                    groups[groupPath] = "cmd" + string.Join("", parts[..i].Select(OperationInfo.ToPascalCase));
                }
            }
        }

        // Emit group command variables
        foreach (var (path, varName) in groups.OrderBy(g => g.Key))
        {
            var parts = path.Split(' ');
            var name = parts[^1];
            var desc = GetGroupDescription(name);
            sb.AppendLine($"        var {varName} = new Command(\"{name}\", \"{desc}\");");
        }

        sb.AppendLine();

        // Wire up group hierarchy
        foreach (var (path, varName) in groups.OrderBy(g => g.Key))
        {
            var parts = path.Split(' ');
            if (parts.Length == 1)
            {
                sb.AppendLine($"        root.Subcommands.Add({varName});");
            }
            else
            {
                var parentPath = string.Join(' ', parts[..^1]);
                var parentVar = groups[parentPath];
                sb.AppendLine($"        {parentVar}.Subcommands.Add({varName});");
            }
        }

        sb.AppendLine();

        // Wire up leaf commands
        foreach (var (parts, className) in leafCommands)
        {
            if (parts.Length == 1)
            {
                sb.AppendLine($"        root.Subcommands.Add({className}.Create());");
            }
            else
            {
                var parentPath = string.Join(' ', parts[..^1]);
                var parentVar = groups[parentPath];
                sb.AppendLine($"        {parentVar}.Subcommands.Add({className}.Create());");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetGroupDescription(string name) => name switch
    {
        "server" => "Commands for managing servers",
        "domain" => "Commands for managing domains",
        "action" => "Commands for managing actions",
        "account" => "Commands for account information",
        "ssh-key" => "Commands for managing SSH keys",
        "image" => "Commands for managing images",
        "load-balancer" => "Commands for managing load balancers",
        "vpc" => "Commands for managing VPCs",
        "region" => "Commands for regions",
        "size" => "Commands for server sizes",
        "software" => "Commands for software information",
        "record" => "Commands for domain records",
        "rule" => "Commands for load balancer rules",
        "firewall" => "Commands for firewall rules",
        "feature" => "Commands for server features",
        "backup" => "Commands for server backups",
        "kernel" => "Commands for server kernels",
        "snapshot" => "Commands for server snapshots",
        "alert" => "Commands for server alerts",
        "invoice" => "Commands for account invoices",
        "data-usage" => "Commands for server data usage",
        "metrics" => "Commands for server metrics",
        "nameservers" => "Commands for domain nameservers",
        "ipv6-ptr-ns" => "Commands for IPv6 PTR nameserver records",
        _ => $"Commands for {name}",
    };
}
